<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();
$customAttribute = $_product->getAttributeText('custom_product_status'); ?>
<?php $buttonTitle = __('Add to Cart');
$translatableText = __('Producto Estandard'); ?>

<?php if($customAttribute == 'discontinued'): ?>

    <div class="container-holder">
        <div class="modal-discontinued" id="modal-product">
            <div class="info-holder">
                <p>Hello World!</p>
            </div>
            <div class="close" onclick="cerrarModal()"></div>
        </div>
        <div class="overlay-discontinued"></div>
    </div>

<?php endif; ?>

<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <input type="hidden" id="status" name="status" value="<?= $customAttribute ?>">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                    name="qty"
                    id="qty"
                    min="0"
                    value="<?= $block->getProductDefaultQty() * 1 ?>"
                    title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                    class="input-text qty"
                    data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />
            </div>
        </div>
        <?php endif; ?>
        <?php if($customAttribute == 'standard') : ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <p><?= $block->escapeHtml($translatableText); ?></p>
                <?= $block->getChildHtml('', true) ?>
            </div>

        <?php elseif($customAttribute == 'pre-order'): ?>
            <div class="actions">
                <button type="button"
                        title=""
                        class="action primary tocart preorder"
                        id="" disabled>
                    <span>Coming Soon</span>
                </button>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>


<script type="text/javascript">
    function cerrarModal(){
        var modal = document.querySelector('.container-holder');
        modal.style.display="none";

    }
</script>
